name: CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: lint
      run: make lint

  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: unit tests
      run: make test
