name: CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: lint
      run: make lint

  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: unit tests
      run: make test

  integration-tests:
    name: integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: set env for go
      run: echo "::add-path::$(go env GOPATH)/bin"

    - name: install bats
      run: sudo npm install -g bats

    - name: integration tests
      run: make integration-tests
