name: CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: lint
      run: make lint
